import Head from 'next/head'
import { Provider } from 'react-redux'
import { createGlobalStyle } from 'styled-components'
import { useStore } from '../store'
import '../styles/globals.scss'

//グローバルのスタイル
const GlobalStyle = createGlobalStyle`
   ol, ul {
    list-style:none;
   }
`

function MyApp({ Component, pageProps }: any) {
  const store = useStore(pageProps.initialReduxState)

  return (
    <>
      <Head>
        <meta key="charset" name="charset" content="utf-8" />
        <meta
          key="viewport"
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=5"
        />
        <meta property="og:locale" content="ja_JP" />
        <meta property="og:type" content="website" />
        <title>Amplify_Next_TMP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <GlobalStyle />
      <Provider store={store}>
        <Component {...pageProps} />
      </Provider>
    </>
  )
}

export default MyApp
